UnicaesGestion/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UnicaesGestion;

namespace UnicaesGestion.Controllers
{
    public class CategoriasController : Controller
    {
        private GestionEntities db = new GestionEntities();

        // GET: Categorias
        public ActionResult Index()
        {
            return View(db.Categorias.ToList());
        }

        // GET: Categorias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // GET: Categorias/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Categorias/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,categoria1")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Categorias.Add(categoria);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(categoria);
        }

        // GET: Categorias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,categoria1")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                db.Entry(categoria).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create");
            }
            return View(categoria);
        }

        // GET: Categorias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Categoria categoria = db.Categorias.Find(id);
            if (categoria == null)
            {
                return HttpNotFound();
            }
            return View(categoria);
        }

        // POST: Categorias/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Categoria categoria = db.Categorias.Find(id);
            db.Categorias.Remove(categoria);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UnicaesGestion/Views/Categorias/Create.cshtml
@model UnicaesGestion.Categoria

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/assets/toastr-master/toastr.css" rel="stylesheet" />
<link href="~/Content/css/tasks.css" rel="stylesheet">

<!--main content start-->
<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <section class="panel tasks-widget">
                <header class="panel-heading">
                   Categoria 
                </header>
                <div class="panel-body">

                    <div class="task-content">

                        <div class="panel-body">

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success col-sm-3 col-lg-2" id="agregarCriterio"><i class="fa fa-plus"> Agregar</i></button>
                                    <div class="col-lg-9">
                                        <div class="input-group m-bot15">
                                            <span class="input-group-btn">
                                                <button class="btn btn-white"><i class="fa  fa-file-o"></i></button>
                                            </span>
                                            @Html.EditorFor(model => model.categoria1, new { htmlAttributes = new { @class = "form-control" , onkeyup="validarCategoria()" , id="categoria"} })
                                        </div>

                                    </div>
                                </div>
                            }
                        </div>
                        @*@Html.Partial("_PartialList", new ViewDataDictionary(@ViewBag.lista))*@
                        @{ Html.RenderAction("Index");}

                    </div>
                </div>
            </section>
        </div>




    </section>
    <!-- page end-->
</section>

<!--main content end-->
<!--Start JavaScript-->
@section JavaScript {
<script src="~/Scripts/views/Validaciones.js"></script>
<script src="~/Content/assets/toastr-master/toastr.js"></script>

}
<!--End JavaScript-->

UnicaesGestion/Views/Categorias/Delete.cshtml
@model UnicaesGestion.Categoria

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Categoria</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.categoria1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.categoria1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UnicaesGestion/Views/Categorias/Details.cshtml
@model UnicaesGestion.Categoria

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <header class="panel-heading">
               Categoria
            </header>



            <div class="panel-body">
                <div class="form">
                    <form class="cmxform form-horizontal tasi-form" >

                        <div class="form-group ">
                            <label for="unidad" class="control-label col-lg-2">Categoria</label>
                            <div class="col-lg-10">
                                <input class=" form-control" name="" id="" value="  @Html.DisplayFor(model => model.categoria1)" type="text" disabled/>                               
                            </div>
                        </div>
                    </form>
                </div>
            </div>



        </section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

UnicaesGestion/Views/Categorias/Edit.cshtml
@model UnicaesGestion.Categoria

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/assets/toastr-master/toastr.css" rel="stylesheet" />

<!--main content start-->

<section id="main-content">
    <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <section class="panel tasks-widget">
                <header class="panel-heading">
                    Editar Categoria
                </header>
                <div class="panel-body">

                    <div class="task-content">

                        <div class="panel-body">

                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    <button type="submit" class="btn btn-success col-sm-3 col-lg-2" id="agregarCriterio"><i class="fa fa-plus"> Editar</i></button>
                                    <div class="col-lg-9">
                                        <div class="input-group m-bot15">
                                            <span class="input-group-btn">
                                                <button class="btn btn-white"><i class="fa  fa-file-o"></i></button>
                                            </span>
                                            @Html.EditorFor(model => model.categoria1, new { htmlAttributes = new { @class = "form-control", id = "categoria" } })
                                        </div>

                                    </div>
                                </div>
                            }
                        </div>
                        @*@Html.Partial("_PartialList", new ViewDataDictionary(@ViewBag.lista))*@
                        @*@{ Html.RenderAction("Index");}*@

                    </div>
                </div>
            </section>
        </div>




    </section>
    <!-- page end-->
</section>

<!--main content end-->

<!--Start JavaScript-->
@section JavaScript {
    <script src="~/Scripts/views/Validaciones.js"></script>
    <script src="~/Content/assets/toastr-master/toastr.js"></script>

}
<!--End JavaScript-->

UnicaesGestion/Views/Categorias/Index.cshtml
@model IEnumerable<UnicaesGestion.Categoria>

@{
    ViewBag.Title = "Index";
    Layout = null;
    //"~/Views/Shared/_Layout.cshtml"
}




<ul id="myUL" class="task-list">
    @foreach (var item in Model)
    {
        <li>

            <div class="task-title">
                <span class="task-title-sp"><a>@Html.DisplayFor(modelItem => item.categoria1)</a></span>

                <div class="pull-right hidden-phone">
                    @*<button onclick="location.href='@Url.Action("Edit", "Categorias", new { id=item.id })'" class="btn btn-success btn-xs"><i class=" fa fa-eye"></i> </button>*@
                    <button onclick="location.href='@Url.Action("Edit", "Categorias", new { id=item.id})'" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
                    <button onclick="location.href='@Url.Action("Delete", "Categorias", new { id=item.id})'" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></button>           
               </div>
            </div>
        </li>

    }
</ul>