UnicaesGestion/Controllers/CatalogoCompetenciasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UnicaesGestion;

namespace UnicaesGestion.Controllers
{
    public class CatalogoCompetenciasController : Controller
    {
        private GestionEntities db = new GestionEntities();

        // GET: CatalogoCompetencias
        public ActionResult Index()
        {
            var catalogoCompetencias = db.CatalogoCompetencias.Include(c => c.Categoria).Include(c => c.TipoPuesto);
            return View(catalogoCompetencias.ToList());
        }

        // GET: CatalogoCompetencias/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CatalogoCompetencia catalogoCompetencia = db.CatalogoCompetencias.Find(id);
            if (catalogoCompetencia == null)
            {
                return HttpNotFound();
            }
            return View(catalogoCompetencia);
        }

        // GET: CatalogoCompetencias/Create
        public ActionResult Create()
        {
            ViewBag.idCategoria = new SelectList(db.Categorias, "id", "categoria1");
            ViewBag.idTipoPuesto = new SelectList(db.TipoPuestoes, "Id", "tipo");
            return View();
        }

        // POST: CatalogoCompetencias/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,competencia,idTipoPuesto,idCategoria")] CatalogoCompetencia catalogoCompetencia)
        {
            if (ModelState.IsValid)
            {
                db.CatalogoCompetencias.Add(catalogoCompetencia);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            ViewBag.idCategoria = new SelectList(db.Categorias, "id", "categoria1", catalogoCompetencia.idCategoria);
            ViewBag.idTipoPuesto = new SelectList(db.TipoPuestoes, "Id", "tipo", catalogoCompetencia.idTipoPuesto);
            return View(catalogoCompetencia);
        }

        // GET: CatalogoCompetencias/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CatalogoCompetencia catalogoCompetencia = db.CatalogoCompetencias.Find(id);
            if (catalogoCompetencia == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCategoria = new SelectList(db.Categorias, "id", "categoria1", catalogoCompetencia.idCategoria);
            ViewBag.idTipoPuesto = new SelectList(db.TipoPuestoes, "Id", "tipo", catalogoCompetencia.idTipoPuesto);
            return View(catalogoCompetencia);
        }

        // POST: CatalogoCompetencias/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,competencia,idTipoPuesto,idCategoria")] CatalogoCompetencia catalogoCompetencia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(catalogoCompetencia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create");
            }
            ViewBag.idCategoria = new SelectList(db.Categorias, "id", "categoria1", catalogoCompetencia.idCategoria);
            ViewBag.idTipoPuesto = new SelectList(db.TipoPuestoes, "Id", "tipo", catalogoCompetencia.idTipoPuesto);
            return View(catalogoCompetencia);
        }

        // GET: CatalogoCompetencias/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CatalogoCompetencia catalogoCompetencia = db.CatalogoCompetencias.Find(id);
            if (catalogoCompetencia == null)
            {
                return HttpNotFound();
            }
            return View(catalogoCompetencia);
        }

        // POST: CatalogoCompetencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CatalogoCompetencia catalogoCompetencia = db.CatalogoCompetencias.Find(id);
            db.CatalogoCompetencias.Remove(catalogoCompetencia);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UnicaesGestion/Views/CatalogoCompetencias/Create.cshtml
@model UnicaesGestion.CatalogoCompetencia

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<link href="~/Content/assets/toastr-master/toastr.css" rel="stylesheet" />
<link rel="stylesheet" href="~/Content/assets/data-tables/DT_bootstrap.css" />

<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <header class="panel-heading">
                Competencias Cardinales y Especificas
            </header>



            <div class="panel-body">
                <div class="form">
                    <form class="cmxform form-horizontal tasi-form" method="post" action="/CatalogoCompetencias/Create">

                        <div class="form-group ">
                            <label for="unidad" class="control-label col-lg-2">Competencia</label>
                            <div class="col-lg-10">
                                <input class=" form-control" id="competencia" name="competencia" type="text" />
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="control-label col-lg-2">Tipo de Puesto</label>
                            <div class="col-lg-10">
                                @Html.DropDownList("idTipoPuesto", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="password" class="control-label col-lg-2">Categoria</label>
                            <div class="col-lg-10">
                                @Html.DropDownList("idCategoria", null, string.Empty, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>


                        <div class="modal-footer clearfix">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-danger" type="submit" value="Create">Agregar</button>
                            </div>
                        </div>

                    </form>

                    @{ Html.RenderAction("Index", "CatalogoCompetencias");}
                </div>
            </div>



        </section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->


@section JavaScript {
    <script src="~/Content/js/ModalFunction.js"></script>
    <script src="~/Content/assets/toastr-master/toastr.js"></script>
    <script src="~/Scripts/views/Validaciones.js"></script>

    <script>
        $(document).ready(function () {
            EditableTable.init();
        });
    </script>
}
<!--End JavaScript-->

UnicaesGestion/Views/CatalogoCompetencias/Delete.cshtml
@model UnicaesGestion.CatalogoCompetencia

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CatalogoCompetencia</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.competencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.competencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categoria.categoria1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categoria.categoria1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoPuesto.tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoPuesto.tipo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UnicaesGestion/Views/CatalogoCompetencias/Details.cshtml
@model UnicaesGestion.CatalogoCompetencia

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <header class="panel-heading">
               Competencias
            </header>

            <div class="panel-body">
                <div class="form">
                    <form class="cmxform form-horizontal tasi-form">

                        <div class="form-group ">
                            <label for="unidad" class="control-label col-lg-2">Competencia</label>
                            <div class="col-lg-10">
                                <input class=" form-control" name="" id="" value="@Html.DisplayFor(model => model.competencia)" type="text" disabled />                     
                            </div>
                        </div>
                        <div class="form-group ">
                            <label for="unidad" class="control-label col-lg-2">Categoria</label>
                            <div class="col-lg-10">
                                <input class=" form-control" name="" id="" value="@Html.DisplayFor(model => model.Categoria.categoria1)" type="text" disabled />
                            </div>
                        </div>
                        <div class="form-group ">
                            <label for="unidad" class="control-label col-lg-2">Tipo de Puesto</label>
                            <div class="col-lg-10">
                                <input class=" form-control" name="" id="" value=" @Html.DisplayFor(model => model.TipoPuesto.tipo)" type="text" disabled/>
                            </div>
                        </div>                       
                    </form>
                </div>
            </div>

        </section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

UnicaesGestion/Views/CatalogoCompetencias/Edit.cshtml
@model UnicaesGestion.CatalogoCompetencia

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/assets/toastr-master/toastr.css" rel="stylesheet" />

<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <header class="panel-heading">
                Editar Competencia
            </header>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="panel-body">
                @*<div class="form">
                    <form class="cmxform form-horizontal tasi-form" method="post" action="/PuestoTrabajoes/Create">*@
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group row">
                        <label for="unidad" class="control-label col-lg-2">Competencia</label>
                        <div class="col-lg-10">
                            @Html.EditorFor(model => model.competencia, new { htmlAttributes = new { @class = "form-control" , id= "competencia" } })
                        </div>
                    </div>

                        <div class="form-group row">
                            <label for="password" class="control-label col-lg-2">Tipo de Puesto</label>
                            <div class="col-lg-10">
                                @Html.DropDownList("idTipoPuesto", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="control-label col-lg-2">Categoria</label>
                            <div class="col-lg-10">
                                @Html.DropDownList("idCategoria", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>

                        


                       

                        <div class="modal-footer clearfix">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-danger" type="submit" value="Save">Guardar</button>
                                <button class="btn btn-default" type="submit" value="Create">Cancelar</button>
                            </div>
                        </div>

                        @*</form>
                            </div>*@
                }
            </div>



        </section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->


@section JavaScript {

    <script src="~/Content/assets/toastr-master/toastr.js"></script>
    <script src="~/Scripts/views/Validaciones.js"></script>

 
}
<!--End JavaScript-->

UnicaesGestion/Views/CatalogoCompetencias/Index.cshtml
@model IEnumerable<UnicaesGestion.CatalogoCompetencia>

@{
    ViewBag.Title = "Index";
    Layout = null;
    //"~/Views/Shared/_Layout.cshtml"
}



<div class="panel-body">
    <div class="adv-table editable-table ">    

        <div class="space15"></div>

        <div class="table-responsive">

            <table class="table table-striped table-hover table-bordered" id="editable-sample">
                <thead>
                    <tr>
                        <th>Competencia</th>
                        <th>Categoria</th>
                        <th>Tipo Puesto</th>
                        <th>Controles      </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.competencia)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Categoria.categoria1)
                            </td>
                            <td>
                              @Html.DisplayFor(modelItem => item.TipoPuesto.tipo)
                            </td>
                            
                            <td>
                                <div class="pull-right hidden-phone">
                                    <button type="submit" value="Delete" onclick="location.href='@Url.Action("Edit", "CatalogoCompetencias", new { id=item.Id })'" class="btn btn-primary btn-xs"><i class=" fa fa-pencil"></i> </button>
                                    <button type="submit" value="Delete" onclick="location.href='@Url.Action("Delete", "CatalogoCompetencias", new { id=item.Id })'" class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></button>
                                    @*<button  onclick="location.href='#myModal'"   class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>*@
                                    @*<button class="btn btn-danger btn-xs" data-toggle="modal" href="#myModal" type="button"><i class="fa fa-trash-o "></i></button>*@
                                </div>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>



        </div>
    </div>
</div>




@*</section>*@
<!-- page end-->
@*</section>
    </section>*@
<!--main content end-->
<!--Start JavaScript-->
@section JavaScript {
    <script src="~/Content/js/ModalFunction.js"></script>

    <script>
        $(document).ready(function () {
            EditableTable.init();
        });
    </script>
}
<!--End JavaScript-->