UnicaesGestion/Controllers/PasoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UnicaesGestion;

namespace UnicaesGestion.Controllers
{
    public class PasoesController : Controller
    {
        private GestionEntities db = new GestionEntities();

        // GET: Pasoes
        public ActionResult Index()
        {
            if (Request.Cookies["llave"] != null)
            {
                int llave;
                if (Request.Cookies["llave"]["idProcedimiento"] != null)
                {
                    llave = int.Parse(Request.Cookies["llave"]["idProcedimiento"].ToString());                   
                    var pasoes = db.Pasoes.Where(p => p.Procedimiento.id==llave).Include(p => p.PuestoTrabajo).Include(p => p.TipoPaso);
                    return View(pasoes.ToList());
                }
            }
            //var pasoes = db.Pasoes.Include(p => p.Procedimiento).Include(p => p.PuestoTrabajo).Include(p => p.TipoPaso);
            return View();
        }

        // GET: Pasoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paso paso = db.Pasoes.Find(id);
            if (paso == null)
            {
                return HttpNotFound();
            }
            return View(paso);
        }

        // GET: Pasoes/Create
        public ActionResult Create()
        {
            if (Request.Cookies["llave"] != null)
            {
                int llave;
                if (Request.Cookies["llave"]["idProcedimiento"] != null)
                {
                    llave = int.Parse(Request.Cookies["llave"]["idProcedimiento"].ToString());
                    ViewBag.idProcedimiento = new SelectList(db.Procedimientoes.Where(x => x.id == llave), "id", "nombre");
                    ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes, "id", "titulo");
                    ViewBag.idTipoPaso = new SelectList(db.TipoPasoes, "id", "tipoPaso1");
                }
                else
                {
                    ViewBag.idProcedimiento = new SelectList(db.Procedimientoes, "id", "nombre");
                    ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes, "id", "titulo");
                    ViewBag.idTipoPaso = new SelectList(db.TipoPasoes, "id", "tipoPaso1");
                }
            }
            
            return View();
        }

        // POST: Pasoes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,numero,descripcion,predecesores,idProcedimiento,idTipoPaso,idPuestoTrabajo")] Paso paso)
        {
            if (ModelState.IsValid)
            {
                db.Pasoes.Add(paso);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            ViewBag.idProcedimiento = new SelectList(db.Procedimientoes, "id", "nombre", paso.idProcedimiento);
            ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes, "id", "titulo", paso.idPuestoTrabajo);
            ViewBag.idTipoPaso = new SelectList(db.TipoPasoes, "id", "tipoPaso1", paso.idTipoPaso);
            return View(paso);
        }

        // GET: Pasoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paso paso = db.Pasoes.Find(id);
            if (paso == null)
            {
                return HttpNotFound();
            }
            ViewBag.idProcedimiento = new SelectList(db.Procedimientoes, "id", "nombre", paso.idProcedimiento);
            ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes, "id", "titulo", paso.idPuestoTrabajo);
            ViewBag.idTipoPaso = new SelectList(db.TipoPasoes, "id", "tipoPaso1", paso.idTipoPaso);
            return View(paso);
        }

        // POST: Pasoes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,numero,descripcion,predecesores,idProcedimiento,idTipoPaso,idPuestoTrabajo")] Paso paso)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paso).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idProcedimiento = new SelectList(db.Procedimientoes, "id", "nombre", paso.idProcedimiento);
            ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes, "id", "titulo", paso.idPuestoTrabajo);
            ViewBag.idTipoPaso = new SelectList(db.TipoPasoes, "id", "tipoPaso1", paso.idTipoPaso);
            return View(paso);
        }

        // GET: Pasoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paso paso = db.Pasoes.Find(id);
            if (paso == null)
            {
                return HttpNotFound();
            }
            return View(paso);
        }

        // POST: Pasoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Paso paso = db.Pasoes.Find(id);
            db.Pasoes.Remove(paso);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UnicaesGestion/Views/Pasoes/Create.cshtml
@model UnicaesGestion.Paso

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!--Corregido-->
<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <header class="panel-heading">
                Pasos de Procedimiento
            </header>

            <div class="panel-body">
                <div class="form">
                    <form class="cmxform form-horizontal tasi-form" id="signupForm" method="Post" action="/Pasoes/Create">
                                <div class="form-group ">
                                    <label for="objetivoF" class="control-label col-lg-2">Procedimiento</label>
                                    <div class="col-lg-10">
                                        @Html.DropDownList("idProcedimiento", null, htmlAttributes: new { @class = "form-control" })
                                    </div>
                                </div>

                                <div class="form-group ">
                                    <label for="procedimiento" class="control-label col-lg-2">Numero</label>
                                    <div class="col-lg-10">
                                        <input type="text" name="numero" value="" />
                                    </div>
                                </div>

                                <div class="form-group ">
                                    <label for="procedimiento" class="control-label col-lg-2">Descripcion</label>
                                    <div class="col-lg-10">
                                        <textarea class="form-control" id="descripcion" name="descripcion" rows="3"> </textarea>
                                    </div>
                                </div>
                                <div class="form-group ">
                                    <label for="objetivoI" class="control-label col-lg-2">Predecesores</label>
                                    <div class="col-lg-10">
                                        <textarea class="form-control" id="predecesores" name="predecesores" rows="3"> </textarea>
                                    </div>
                                </div>
                              
                                <div class="form-group ">
                                    <label for="objetivoF" class="control-label col-lg-2">Figura</label>
                                    <div class="col-lg-10">
                                        @Html.DropDownList("idTipoPaso", null, htmlAttributes: new { @class = "form-control" })
                                    </div>
                                </div>
                            
                                <div class="form-group ">
                                    <label for="objetivoF" class="control-label col-lg-2">Responsable</label>
                                    <div class="col-lg-10">
                                        @Html.DropDownList("idPuestoTrabajo", null, htmlAttributes: new { @class = "form-control" })
                                    </div>
                                </div>

                                <div class="modal-footer">
                                    <div class="col-lg-offset-2 col-lg-10">
                                        <button class="btn btn-danger" type="submit" value="Create">Guardar</button>
                                        <button class="btn btn-default" type="submit" value="Create">Cancelar</button>
                                    </div>
                                </div>

                    </form>
                </div>
                @{ Html.RenderAction("Index", "Pasoes");}

                <div class="modal-footer">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button class="btn btn-danger" type="submit" value="Create">Finalizar</button>                     
                    </div>
                </div>
            </div>


        </section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->


<!--Start JavaScript-->
@section JavaScript {
    <script src="~/Content/js/ModalFunction.js"></script>
    @*<script>
           function Enviar() {
            $('#funcion')[0].submit(function (event) {
             alert("Handler for .submit() called.");
             event.preventDefault();
            });
          }

        </script>*@

    <script>
        $(document).ready(function () {
            EditableTable.init();
        });
    </script>



    <script>
        $(".eliminar").click(function () {
             var clave = $(this).data("funcion-id")
             var valor = { "id": clave }


             var nuevo = $($($(this).parent()).parent()).parent()
             $(this).closest('tr').remove();
                 console.log(nuevo)

            $.ajax({
                type: "Post",
                url: "/Pasoes/Delete",
                data: valor,
                success: function () {
                    console.log("ok")
                },
                error: function () { }

            })
        })

    </script>

}

@*<h2>Create</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Paso</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.numero, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.numero, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.predecesores, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.predecesores, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.predecesores, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idProcedimiento, "idProcedimiento", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idProcedimiento", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idProcedimiento, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idTipoPaso, "idTipoPaso", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idTipoPaso", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idTipoPaso, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idPuestoTrabajo, "idPuestoTrabajo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idPuestoTrabajo", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idPuestoTrabajo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

UnicaesGestion/Views/Pasoes/Delete.cshtml
@model UnicaesGestion.Paso

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Paso</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.predecesores)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.predecesores)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Procedimiento.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Procedimiento.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PuestoTrabajo.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PuestoTrabajo.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoPaso.tipoPaso1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoPaso.tipoPaso1)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UnicaesGestion/Views/Pasoes/Details.cshtml
@model UnicaesGestion.Paso

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Paso</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.numero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.numero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.predecesores)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.predecesores)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Procedimiento.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Procedimiento.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PuestoTrabajo.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PuestoTrabajo.titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoPaso.tipoPaso1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoPaso.tipoPaso1)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UnicaesGestion/Views/Pasoes/Edit.cshtml
@model UnicaesGestion.Paso

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<!--Corregido-->
<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <header class="panel-heading">
              Editar Paso
            </header>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)
            <div class="panel-body">
                @*<div class="form">
                    <form class="cmxform form-horizontal tasi-form" id="signupForm" method="Post" action="/Pasoes/Create">*@
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                        <div class="form-group row">
                            <label for="procedimiento" class="control-label col-lg-2">Numero</label>
                            <div class="col-lg-10">
                                @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="procedimiento" class="control-label col-lg-2">Descripcion</label>
                            <div class="col-lg-10">
                                @Html.TextAreaFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="objetivoI" class="control-label col-lg-2">Predecesores</label>
                            <div class="col-lg-10">
                                @Html.EditorFor(model => model.predecesores, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="objetivoF" class="control-label col-lg-2">Procedimiento</label>
                            <div class="col-lg-10">
                                @Html.DropDownList("idProcedimiento", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group row ">
                            <label for="objetivoF" class="control-label col-lg-2">Tipo Paso</label>
                            <div class="col-lg-10">
                                @Html.DropDownList("idTipoPaso", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="objetivoF" class="control-label col-lg-2">Tipo Paso</label>
                            <div class="col-lg-10">
                                @Html.DropDownList("idPuestoTrabajo", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-danger" type="submit" value="Create">Guardar</button>
                                <button class="btn btn-default" type="submit" value="Create">Cancelar</button>
                            </div>
                        </div>

                    @*</form>
                </div>*@
                }
            </div>


        </section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

@*<h2>Edit</h2>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Paso</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.id)

            <div class="form-group">
                @Html.LabelFor(model => model.numero, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.numero, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.descripcion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.descripcion, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.predecesores, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.predecesores, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.predecesores, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idProcedimiento, "idProcedimiento", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idProcedimiento", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idProcedimiento, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idTipoPaso, "idTipoPaso", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idTipoPaso", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idTipoPaso, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.idPuestoTrabajo, "idPuestoTrabajo", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("idPuestoTrabajo", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.idPuestoTrabajo, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>*@

UnicaesGestion/Views/Pasoes/Index.cshtml
@model IEnumerable<UnicaesGestion.Paso>

@{
    ViewBag.Title = "Index";
    Layout = null;
}
@*"~/Views/Shared/_Layout.cshtml"*@


<style>
    .oculta {
        display: none;
    }

    .eliminar {
    }
</style>



            <div class="panel-body">
                <div class="adv-table editable-table ">
                    @*<div class="clearfix">
                        <div class="btn-group">
                            <button class="btn btn-danger" data-toggle="modal" href="#myModal" type="button">
                                Agregar Paso <i class="fa fa-plus"></i>
                            </button>
                        </div>
                    </div>*@


                    <div class="space15"></div>

                    <div class="table-responsive">

                        <table class="table table-striped table-hover table-bordered" id="editable-sample">
                            <thead>
                                <tr>
                                    <th>Paso</th>
                                    <th>Resposable</th>
                                    <th>Descripción</th>
                                    <th>Predecesor</th>
                                    <th>Figura</th>
                                    <th>Controles      </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.numero)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.PuestoTrabajo.titulo)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.descripcion)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.predecesores)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.TipoPaso.tipoPaso1)
                                        </td>
                                        
                                       
                                        
                                        <td>
                                            <div class="pull-right hidden-phone">
                                                <button type="submit" value="Delete" onclick="location.href='@Url.Action("Edit", "Pasoes", new { id=item.id })'" class="btn btn-success btn-xs"><i class=" fa fa-pencil"></i> </button>
                                                <button class="btn btn-danger btn-xs eliminar" data-funcion-id="@Html.DisplayFor(modelItem=> item.id)" type="button"><i class="fa fa-trash-o "></i></button>
                                                @*<button  onclick="location.href='#myModal'"   class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>*@
                                                @*<button class="btn btn-danger btn-xs" data-toggle="modal" href="#myModal" type="button"><i class="fa fa-trash-o "></i></button>*@
                                            </div>
                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>

                      

                    </div>
                </div>
            </div>


            

        @*</section>*@
        <!-- page end-->
    @*</section>
</section>*@
<!--main content end-->
<!--Start JavaScript-->
@section JavaScript {
    <script src="~/Content/js/ModalFunction.js"></script>

    <script>
        $(document).ready(function () {
            EditableTable.init();
        });
    </script>
}
<!--End JavaScript-->

@*<h2>Index</h2>

    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.numero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.predecesores)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Procedimiento.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PuestoTrabajo.titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoPaso.tipoPaso1)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.numero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.predecesores)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Procedimiento.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PuestoTrabajo.titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TipoPaso.tipoPaso1)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
                @Html.ActionLink("Details", "Details", new { id=item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.id })
            </td>
        </tr>
    }

    </table>*@