UnicaesGestion/Controllers/CompetenciaPuestoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UnicaesGestion;

namespace UnicaesGestion.Controllers
{
    public class CompetenciaPuestoController : Controller
    {
        private GestionEntities db = new GestionEntities();

        // GET: CompetenciaPuesto
        public ActionResult Index()
        {
            if (Request.Cookies["llave"] != null)
            {
                int llave;
                if (Request.Cookies["llave"]["idPuestoTrabajo"] != null)
                {
                    llave = int.Parse(Request.Cookies["llave"]["idPuestoTrabajo"].ToString());
                    var competenciaPuestoTrabajoes = db.CompetenciaPuestoTrabajoes.Include(c => c.CatalogoCompetencia).Where(r => r.PuestoTrabajo.id == llave);
                    return View(competenciaPuestoTrabajoes.ToList());
                }
            }
            return View();

            //var competenciaPuestoTrabajoes = db.CompetenciaPuestoTrabajoes.Include(c => c.CatalogoCompetencia).Include(c => c.PuestoTrabajo);
           
        }

        // GET: CompetenciaPuesto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompetenciaPuestoTrabajo competenciaPuestoTrabajo = db.CompetenciaPuestoTrabajoes.Find(id);
            if (competenciaPuestoTrabajo == null)
            {
                return HttpNotFound();
            }
            return View(competenciaPuestoTrabajo);
        }

        // GET: CompetenciaPuesto/Create
        public ActionResult Create()
        {
            if (Request.Cookies["llave"] != null)
            {
                int llave;
                if (Request.Cookies["llave"]["idPuestoTrabajo"] != null)
                {
                    llave = int.Parse(Request.Cookies["llave"]["idPuestoTrabajo"].ToString());
                    ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes.Where(x => x.id == llave), "id", "titulo");
                    ViewBag.idCompetencia = new SelectList(db.CatalogoCompetencias, "Id", "competencia");
                }
                else
                {
                    ViewBag.idCompetencia = new SelectList(db.CatalogoCompetencias, "Id", "competencia");
                    ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes, "id", "titulo");
                }
            }

            //ViewBag.idCompetencia = new SelectList(db.CatalogoCompetencias, "Id", "competencia");
            //ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes, "id", "titulo");
            return View();
        }

        // POST: CompetenciaPuesto/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,idCompetencia,idPuestoTrabajo,escencial")] CompetenciaPuestoTrabajo competenciaPuestoTrabajo)
        {
            if (ModelState.IsValid)
            {
                db.CompetenciaPuestoTrabajoes.Add(competenciaPuestoTrabajo);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            ViewBag.idCompetencia = new SelectList(db.CatalogoCompetencias, "Id", "competencia", competenciaPuestoTrabajo.idCompetencia);
            ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes, "id", "titulo", competenciaPuestoTrabajo.idPuestoTrabajo);
            return View(competenciaPuestoTrabajo);
        }

        // GET: CompetenciaPuesto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompetenciaPuestoTrabajo competenciaPuestoTrabajo = db.CompetenciaPuestoTrabajoes.Find(id);
            if (competenciaPuestoTrabajo == null)
            {
                return HttpNotFound();
            }
            ViewBag.idCompetencia = new SelectList(db.CatalogoCompetencias, "Id", "competencia", competenciaPuestoTrabajo.idCompetencia);
            ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes, "id", "titulo", competenciaPuestoTrabajo.idPuestoTrabajo);
            return View(competenciaPuestoTrabajo);
        }

        // POST: CompetenciaPuesto/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,idCompetencia,idPuestoTrabajo,escencial")] CompetenciaPuestoTrabajo competenciaPuestoTrabajo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(competenciaPuestoTrabajo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idCompetencia = new SelectList(db.CatalogoCompetencias, "Id", "competencia", competenciaPuestoTrabajo.idCompetencia);
            ViewBag.idPuestoTrabajo = new SelectList(db.PuestoTrabajoes, "id", "titulo", competenciaPuestoTrabajo.idPuestoTrabajo);
            return View(competenciaPuestoTrabajo);
        }

        // GET: CompetenciaPuesto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CompetenciaPuestoTrabajo competenciaPuestoTrabajo = db.CompetenciaPuestoTrabajoes.Find(id);
            if (competenciaPuestoTrabajo == null)
            {
                return HttpNotFound();
            }
            return View(competenciaPuestoTrabajo);
        }

        // POST: CompetenciaPuesto/Delete/5
        [HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CompetenciaPuestoTrabajo competenciaPuestoTrabajo = db.CompetenciaPuestoTrabajoes.Find(id);
            db.CompetenciaPuestoTrabajoes.Remove(competenciaPuestoTrabajo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UnicaesGestion/Views/CompetenciaPuesto/Create.cshtml
@model UnicaesGestion.CompetenciaPuestoTrabajo

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<link rel="stylesheet" href="~/Content/assets/data-tables/DT_bootstrap.css" />

<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <header class="panel-heading">
                Competencias Cardinales y Especificas
            </header>



            <div class="panel-body">
                <div class="form">
                    <form class="cmxform form-horizontal tasi-form" method="post" action="/CompetenciaPuesto/Create">


                        <div class="form-group ">
                            <label for="password" class="control-label col-lg-2">Puesto Trabajo</label>
                            <div class="col-lg-10">
                                @Html.DropDownList("idPuestoTrabajo", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="control-label col-lg-2">Competencia</label>
                            <div class="col-lg-10">
                                @Html.DropDownList("idCompetencia", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group ">
                            <label for="unidad" class="control-label col-lg-2">Esencial</label>
                            <div class="col-lg-10">
                                @Html.EditorFor(model => model.escencial)
                            </div>
                        </div>



                        <div class="modal-footer">
                            <div class="col-lg-offset-2 col-lg-10">
                                <button class="btn btn-danger" type="submit" value="Create">Agregar</button>
                               
                            </div>
                        </div>

                    </form>

                    @{ Html.RenderAction("Index", "CompetenciaPuesto");}
                </div>
                <div class="modal-footer">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button class="btn btn-danger" type="submit" value="Create">Finalizar</button>
                       
                    </div>
                </div>
            </div>



        </section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

@section JavaScript {
<script>
        $(".eliminar").click(function () {
             var clave = $(this).data("funcion-id")
             var valor = { "id": clave }
             var nuevo = $($($(this).parent()).parent()).parent()
             $(this).closest('tr').remove();
                 console.log(nuevo)

            $.ajax({
                type: "Post",
                url: "/CompetenciaPuesto/Delete",
                data: valor,
                success: function () {
                    console.log("ok")
                },
                error: function () { }

            })
        })

</script>
}

UnicaesGestion/Views/CompetenciaPuesto/Delete.cshtml
@model UnicaesGestion.CompetenciaPuestoTrabajo

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompetenciaPuestoTrabajo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.escencial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.escencial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CatalogoCompetencia.competencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CatalogoCompetencia.competencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PuestoTrabajo.titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PuestoTrabajo.titulo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UnicaesGestion/Views/CompetenciaPuesto/Details.cshtml
@model UnicaesGestion.CompetenciaPuestoTrabajo

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!--main content start-->
<section id="main-content">
    <section class="wrapper site-min-height">
        <!-- page start-->
        <section class="panel">
            <header class="panel-heading">
                Competencia Puesto
            </header>



            <div class="panel-body">
                <div class="form">
                    <form class="cmxform form-horizontal tasi-form">

                        <div class="form-group ">
                            <label for="unidad" class="control-label col-lg-2">Competencia</label>
                            <div class="col-lg-10">
                                <input class=" form-control" name="" id="" value="  @Html.DisplayFor(model => model.CatalogoCompetencia.competencia)" type="text" disabled />
                            </div>
                        </div>
                        <div class="form-group ">
                            <label for="unidad" class="control-label col-lg-2">Categoria</label>
                            <div class="col-lg-10">
                                <input class=" form-control" name="" id="" value="@Html.DisplayFor(model => model.escencial)" type="text" disabled />                               
                            </div>
                        </div>
                        <div class="form-group ">
                            <label for="unidad" class="control-label col-lg-2">Tipo de Puesto</label>
                            <div class="col-lg-10">
                                <input class=" form-control" name="" id="" value="@Html.DisplayFor(model => model.PuestoTrabajo.titulo)" type="text" disabled />
                            </div>
                        </div>
                    </form>
                </div>
            </div>



        </section>
        <!-- page end-->
    </section>
</section>
<!--main content end-->

UnicaesGestion/Views/CompetenciaPuesto/Edit.cshtml
@model UnicaesGestion.CompetenciaPuestoTrabajo

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CompetenciaPuestoTrabajo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.idCompetencia, "idCompetencia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCompetencia", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCompetencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idPuestoTrabajo, "idPuestoTrabajo", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idPuestoTrabajo", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idPuestoTrabajo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.escencial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.escencial)
                    @Html.ValidationMessageFor(model => model.escencial, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UnicaesGestion/Views/CompetenciaPuesto/Index.cshtml
@model IEnumerable<UnicaesGestion.CompetenciaPuestoTrabajo>

@{
    ViewBag.Title = "Index";
    Layout = null;
    //"~/Views/Shared/_Layout.cshtml"
}

<style>
    .oculta {
        display: none;
    }

    /*solo para utilizar el boton eliminar Post*/
    .eliminar {
    }
</style>




@*<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.escencial)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CatalogoCompetencia.competencia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PuestoTrabajo.titulo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.escencial)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CatalogoCompetencia.competencia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PuestoTrabajo.titulo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>*@

<div class="panel-body">
    <div class="adv-table editable-table ">
        <header class="panel-heading">
            Competencias Cardinales
        </header>
        <br />

        <div class="space15"></div>

        <div class="table-responsive">

            <table class="table table-bordered table-striped table-advance table-hover">
                <thead>
                    <tr>
                        <th><span>Competencia</span></th>
                        <th><span>Esencial</span></th>
                        <th>
                            <button class="btn btn-danger btn-sm" data-toggle="modal" href="#myModal3" type="button">
                                <i class="fa fa-plus"></i>
                            </button>
                        </th>

                    </tr>
                </thead>
                <tbody>



                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CatalogoCompetencia.competencia)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.escencial)
                            </td>
                            <td>
                                <div class="pull-right hidden-phone">
                                    <button type="submit" value="Delete" onclick="location.href='@Url.Action("Edit", "CompetenciaPuesto", new { id=item.Id })'" class="btn btn-success btn-xs"><i class=" fa fa-pencil"></i> </button>
                                    <button class="btn btn-danger btn-xs eliminar" data-funcion-id="@Html.DisplayFor(modelItem=> item.Id)" type="button"><i class="fa fa-trash-o "></i></button>
                                    @*<button  onclick="location.href='#myModal'"   class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>*@
                                    @*<button class="btn btn-danger btn-xs" data-toggle="modal" href="#myModal" type="button"><i class="fa fa-trash-o "></i></button>*@
                                </div>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>

        </div>
        <!--Tabla2-->

        <div class="table-responsive">
            <header class="panel-heading">
                Competencias Especificas
            </header>

            <table class="table table-bordered table-striped table-advance table-hover">
                <thead>
                    <tr>
                        <th><span>Competencia</span></th>
                        <th><span>Esencial</span></th>
                        <th>
                            <button class="btn btn-danger btn-sm" data-toggle="modal" href="#myModal3" type="button">
                                <i class="fa fa-plus"></i>
                            </button>
                        </th>

                    </tr>
                </thead>
                <tbody>



                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.CatalogoCompetencia.competencia)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.escencial)
                            </td>
                            <td>
                                <div class="pull-right hidden-phone">
                                    <button type="submit" value="Delete" onclick="location.href='@Url.Action("Edit", "CompetenciaPuesto", new { id=item.Id })'" class="btn btn-success btn-xs"><i class=" fa fa-pencil"></i> </button>
                                    <button class="btn btn-danger btn-xs eliminar" data-funcion-id="@Html.DisplayFor(modelItem=> item.Id)" type="button"><i class="fa fa-trash-o "></i></button>
                                    @*<button  onclick="location.href='#myModal'"   class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>*@
                                    @*<button class="btn btn-danger btn-xs" data-toggle="modal" href="#myModal" type="button"><i class="fa fa-trash-o "></i></button>*@
                                </div>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>

        </div>
        <!--End-->









    </div>
</div>